### ISSUE TITLE
Null file size in sFile structure on Call Plugin event

### ISSUE THREAD

**Issue by MetLob** [pleonex/tinke#14]
When I call my plugin from "Call Plugin", file size is null (0) and file format is "Palette". 
Why not "Unknown"?

![clipboard02](https://cloud.githubusercontent.com/assets/12542905/9219732/694ed7ca-40f6-11e5-9b7b-5ad5414abb7d.jpg)

**Comment by pleonex** [comment]
This is bug, in [line 147 from Acciones.cs](https://github.com/pleonex/tinke/blob/master/Tinke/Acciones.cs#L147) I didn't set those fields.

**Comment by pleonex** [comment]
It should be fixed with 674f030, can you try again?

**Comment by MetLob** [comment]
Yea, its OK
