### ISSUE TITLE
Incorrect ROM size in .nds file header after saving rom

### ISSUE THREAD

**Issue by MetLob** [pleonex/tinke#16]
If a changes files in rom (with "Change file" button) and rom data size of new ROM increases.
Then after saving field with data size of the new rom in .nds header (0x80) has been not changed.

In this data size should be change and recalculate all CRC16.
Value of size must be = bigest offset of file (in fat) + size of this file.

**Comment by pleonex** [comment]
You are right. I was updating only the field at 0x14.
