### ISSUE TITLE
Question about Decompress(byte[] data) function in PluginHost

### ISSUE THREAD

**Issue by MetLob** [pleonex/tinke#17]
How I can be use of this function? *PluginHost.cs* line 142
```c#
public void Decompress(byte[] data)
        {
            string temp = Get_TempFile();
        	System.IO.File.WriteAllBytes(temp, data);
        	DescompressEvent(temp);
            try { System.IO.File.Delete(temp); }
            catch { }
        }
```
How get or find of decompressed data? Or temp file name?

**Comment by pleonex** [comment]
In the *LAYTON* plugin, in the *Ani* file format you have an example about how to call the decompression plugins (I have translated the code to English and improved it):
```c#
// Decompress file data removing the first 4 bytes
// Get data to decompress
byte[] compressData = new byte[(new FileInfo(filepath).Length) - 4];
Array.Copy(File.ReadAllBytes(filepath), 4, compressData, 0, compressData.Length); 

// Send the file or data for decompression
pluginHost.Decompress(compressData);

// Get a temp file with the decompressed data
string fileWithDecompressData = pluginHost.Get_Files().files[0].path;
```

The data to decompress will be written into a temp file and send to the plugins (similar to a `CallPlugin()`). All the plugins will check if they support the data (usually checking the first 4 bytes) and if so and the type is `Pack` or `Compressed`, Tinke will call it.

The decompressed data can be access with the function `pluginHost.Get_Files()`. This returns a list of files with the result of the last operation. In the case of decompressing a file there will be only one but if the type was `Pack`, like `NARC`, there will be all the subfiles.

Feel free to close the comment if you don't have more questions :wink:

**Comment by MetLob** [comment]
Very thanks for your answer!
