### ISSUE TITLE
Partitions of OBJs characters don't supported.

### ISSUE THREAD

**Issue by MetLob** [pleonex/tinke#18]
**About partitions:**
- This values for every banks exists in files with the NCER format if value at 0x14 file position > 0.
- Value at 0x14 file position is the offset in NCER file to partitions info block: partition offset (UInt32), partition data size (UInt32). And shouldn't calculating tilePos!
- For every bank tiles data is a partition block of the global tiles file.

Then Bank.partitionOffset must be using in next methods of Ekona.Images:
0) put new variable in Bank structure: partitionOffset (and may be partitionDataSize).
a) **Actions.cs: GetImage(Bank ...)**

            cell_img.StartByte = (int)(tileOffset * 0x20 + bank.partitionOffset);

b) **SpriteControl.cs: Import_File(string path, int banki)** 
            
            uint addedSize = 0;
            ...
            // Get the data of a oam and add to the end of the image
            for (int i = 0; i < oams.Length; i++)
            {
                ...
                // If Add image is checked add the new image to the end of the original file...

*No, adding a new image to the end of the partition block.
In this should be wroten other Add_Image method with insert data position.*

                if (radioImgAdd.Checked)
                {
                    uint offset = Actions.Add_Image(ref imgData, cellImg, (uint)(1 << (int)sprite.BlockSize) * 0x20) - sprite.Banks[banki].partitionOffset;
                    offset /= 0x20;
                    offset >>= (int)sprite.BlockSize;
                    
                    addedSize += cellImg.Length;
                    if (offset >= 0x400) throw new Exception("???");
                    
                    oams[i].obj2.tileOffset = offset;
                    oams[i].obj1.flipX = 0;
                    oams[i].obj1.flipY = 0;
                }
                else   // Replace the old image
                {
                    uint tileOffset = oams[i].obj2.tileOffset;
                    tileOffset = (uint)(tileOffset << (byte)sprite.BlockSize) * 0x20 + sprite.Banks[banki].partitionOffset;
                    Array.Copy(cellImg, 0, imgData, tileOffset, cellImg.Length);
                }
             }
             
             if (addedSize > 0)
                 for (int i = banki + 1; i < sprite.Banks.Length; i++) sprite.Banks[i].partitionOffset += addedSize;

c) **several changes in the NCER.cs of the Images plugin**   
see:   https://groups.google.com/forum/#!topic/tinke/q8Nt88UJ5zQ

**Comment by MetLob** [comment]
I testing this implementation localy.
Replace call Actions.Add_Image to new Insert_Image...

Now, changed SpriteControl and several methods from Actions I copied to my plugins...
But I wont to insert this changes and property "PartitionOffset" in the Bank structure of the base Ekona classes.
And close issue #19 without changes.

**Comment by pleonex** [comment]
Thank you, I was aware about that in 0x14 there were an offset but I couldn't find any file with a non-zero value (in [NinoImager](https://github.com/pleonex/ninoimager/blob/master/ninoimager/Format/Implementation/Ncer.cs#L144) there is a better implementation of NCER format).

Can you give me some NCER files with that field or the name of the game that contains them?
If you want, you can try to implement the feature and make a pull request :)

**Comment by MetLob** [comment]
I look this version of NCER in the Giana Sisters DS (AchievementTexts.NCER, MapTooltips.NCER, TutorialSign.NCER)...
and others with custom sprite formats but convertible to Nitro OBJ (SpriteBase) format...

I can try to implement this at this week... (remove code from plugin to Ekona)

**Comment by pleonex** [comment]
Fixed in #21
