### ISSUE TITLE
Wrong calculation of a Threshold distance

### ISSUE THREAD

**Issue by MetLob** [pleonex/tinke#20]
public static int FindNextColor(Color c, Color[] palette, decimal threshold = 0)
in Ekona.Images.Actions.cs

If a color represented as vector with coordinates R G B
Distance between two vector equals to |x - y|
Then the threshold value is a radius of a toleranced sphere.

But in the FindNextColor method distance calculated as | |x| - |y| |...

Error or I'm not understanding of a color spectre stucture...

**Comment by MetLob** [comment]
I think, next changes fix this:

Old code:

                double modulec = Math.Sqrt(palette[i].R * palette[i].R + palette[i].G * palette[i].G + palette[i].B * palette[i].B);
                decimal distance = (decimal)Math.Abs(module - modulec);

New code:

                double x = palette[i].R - c.R;
                double y = palette[i].G - c.G;
                double z = palette[i].B - c.B;
                decimal distance = (decimal)Math.Sqrt(x * x + y * y + z * z);

**Comment by pleonex** [comment]
You are absolutely right! I will fix it.
