### ISSUE TITLE
Question about Horizontal and Linear bytes convert

### ISSUE THREAD

**Issue by MetLob** [pleonex/tinke#22]
I always confuse the two methods: LinearToHorizontal and inverse.
I understand that LinearToHorizontal converts linear bytes order to tiled... but
for images this is backward action.

For example, LinearToHorizontal method:
I loaded a Bitmap image and I want to get tiled bytes order.
After Indexing of the my bmp Image I have linear bytes order. Allright?
First row of the my image is first bytes...

But for my result tiled image (first bytes must be from first tile) I use HorizontalToLinear method, because LinearToHorizontal take first bytes of 1 tile (from linear image?) and reordered this bytes as for linear image... 

Sorry for the issue... :)
I understand your logic of this methods... now :)

**Comment by pleonex** [comment]
No problem. Let me know if you have further questions.

To clarify: an image can have the pixels organized in several formats:
* Lineal: The pixels are in rows order.
* Horizontal: The pixels are in blocks of 8x8 pixels (a tile). The next tile will be at the right of the previous one.
* Vertical: The pixels are in blocks of 8x8 pixels. The next tile will be below the previous one.

In case this is confusing, in NinoImager [I implemented](https://github.com/pleonex/ninoimager/blob/master/ninoimager/Format/PixelEncoding.cs#L51) this in just one generic converter. The `GetIndex` function will convert a position in the image into Lineal, Horizontal or Vertical formats. Furthermore, this function is generic to any tile size, so it would be great to implement it in Tinke.
