### ISSUE TITLE
Invalid "Header CRC" after resaving trimmed rom (from ndstool)

### ISSUE THREAD

**Issue by MetLob** [pleonex/tinke#41]
After opening and saving (without changes) trimmed rom (fo example after ndstool) "header crc" has invalid value, but recalculated. Header size value is OK. Therefore I don't reopening issue #16.

After opening the newest rom and saving I get a valid rom.

**Comment by pleonex** [comment]
I found the issue. I am setting the ROM size after calculating the CRC value, so if that value changes (trimmed ROMs) the CRC will be invalid. Fixing it.

**Comment by pleonex** [comment]
Fixed, @MetLob can you test it? Thanks for reporting!

**Comment by MetLob** [comment]
This testet. 
Everything is working!
