### ISSUE TITLE
compile.sh fails on paths with spaces in them.

### ISSUE THREAD

**Issue by AliceTheGorgon** [pleonex/tinke#47]
This one's a two-parter.

**The first** (and most easily fixable) part is that the script outputs the following error when checking for a previous build dir:
`./compile.sh: line 38: [: /home/alicethegorgon/Projects/DS: binary operator expected`

The solution is to change:

``` bash
# Remove previous builds
if [ -d $BUILD_DIR ]; then
    echo "Deleting old build directory"
    rm -rf $BUILD_DIR
fi
```

into:

``` bash
# Remove previous builds
if [ -d "$BUILD_DIR" ]; then
    echo "Deleting old build directory"
    rm -rf "$BUILD_DIR"
fi
```

(Note the quotation marks around both instances of `$BUILD_DIR` in the fixed one.)

**The second** problem is that xbuild errors out when compiling plugins, and gives the following error:

```
Compiling plugin Plugins/LAYTON/LAYTON.sln...
Error compiling Plugins/LAYTON/LAYTON.sln. Aborting.
MSBUILD: error MSBUILD0004: Too many project files specified
```

The solution seems to be getting rid of the line:

``` bash
XBUILD_PLUGINS="$XBUILD;OutputPath=$BUILD_DIR/Plugins/"
```

And changing:

``` bash
$XBUILD_PLUGINS "$1" > build.log
```

into:

``` bash
$XBUILD "/p:OutputPath=$BUILD_DIR/Plugins/" "$1" > build.log
```

So that it follows the same format as the (working) compilation of tinke.

I have no idea why you can't just change the XBUILD_PLUGINS definition from:

``` bash
XBUILD_PLUGINS="$XBUILD;OutputPath=$BUILD_DIR/Plugins/"
```

into:

``` bash
XBUILD_PLUGINS="$XBUILD /p:OutputPath=$BUILD_DIR/Plugins/"
```

but for some reason it doesn't work, and gives the same "Too many project files" error.

Also, sorry for not submitting a pull request with these changes. I'm pretty new to git, and it's late, and I really don't want to delve into that whole process right now.
I've attached the modified file though, so it should be easy to toss into the directory and compare and push the changes. (Github won't let me upload it as  a ".sh" file, so I've zipped it up first.)
[compile.sh.zip](https://github.com/pleonex/tinke/files/389783/compile.sh.zip)

**Comment by ccawley2011** [comment]
Added as part of pull request #46.
