### ISSUE TITLE
Recognise files by content, as well as by file extension?

### ISSUE THREAD

**Issue by gingerbeardman** [pleonex/tinke#51]
(I'm running Tinke through Wine Mono on Mac OS X using the Crossover app)

Hi, I am hacking Pang DS rom file.
https://en.wikipedia.org/wiki/Pang:_Magical_Michael

Files are named as follows:
filename_type_compression.bin

for example:
block_ncg_LZ.bin
block_ncl_LZ.bin
stage461b_nsc_LZ.bin
stage461t_nsc_LZ.bin

In Tinke 0.8.1 these files were correctly opened by:
* decompress
* open
- type was automatically figured out by Tinke

In Tinke 0.9.0 these files cannot be opened easily
If I "unpack" I can see the header bytes of each file:

for example:
block_ncg_LZ.bin [RGCN]
block_ncl_LZ.bin [RLCN]
stage461b_nsc_LZ.bin [RCSN]
stage461t_nsc_LZ.bin [RCSN]

It would be good if 0.9.x could recognise these files by content if there is no filename match?
"Recognized files" drops from 99% in 0.8.1 to 98% in 0.9.0

Otherwise, what do I have to do to easily open these file types in 0.9.x?

Thought: is it possible my plugins folder is not being found for some reason?

Thanks!

0.8.1
<img width="1273" alt="screen shot 2017-04-15 at 22 49 43" src="https://cloud.githubusercontent.com/assets/49612/25066999/02ee96b2-222e-11e7-9ec2-54bb0d5c5113.png">

0.9.0
<img width="756" alt="screen shot 2017-04-15 at 22 47 49" src="https://cloud.githubusercontent.com/assets/49612/25066998/fb7b5136-222d-11e7-9cf3-25a6b0da8065.png">

**Comment by pleonex** [comment]
It should recognize the files by content too. In fact, the code didn't change: [Main.cs](https://github.com/pleonex/tinke/blob/master/Plugins/Images/Images/Main.cs#L77) from Images plugin.
Can you double-check that the Plugins folder contains the file *Images.dll*?

**Comment by gingerbeardman** [comment]
Hi, all plugins are there.

so it would seem that running 0.8.2 and 0.9.0 using Wine Mono my plugins directory is not found?

I have run all 3 versions the same way, and only 0.8.1 sees its plugin folder.

**Comment by pleonex** [comment]
Why are you running Mono on Wine? Can you try to run Tinke just with Mono? For instance:
```
mono Tinke.exe [optionalPathToROM]
```

**Comment by pleonex** [comment]
I have just remembered there was an issue in 0.9.0 and Tinke wasn't able to find some plugins because a bug in Mono. In c5f5671bb0b63a4c707efcdabd823a7b6ea87b01 I implemented a workaround. Tinke 0.9.1 and up should work.

**Comment by gingerbeardman** [comment]
Thanks for the tip!

No idea why I was not running it through Mono that way, I guess I first ran Tinke in a VM and never thought to change? Anyway.

It's now running natively on my Mac, albeit with some window redraw issues. Thanks for help so far

![screen shot 2017-04-18 at 15 47 42](https://cloud.githubusercontent.com/assets/49612/25137016/7161c836-244e-11e7-8cb2-45673cbc5e54.png)

**Comment by gingerbeardman** [comment]
@pleonex shall I open issues for these rendering problems?
