### ISSUE TITLE
exe for 0.9.1?

### ISSUE THREAD

**Issue by gingerbeardman** [pleonex/tinke#52]
Could this please be added to the release? 

I cannot compile myself.

Thanks

**Comment by pleonex** [comment]
I think I fixed a problem building the code from Linux (using Mono). But I couldn't test yet if this is working on Windows. Can you try the following binaries?

[Tinke-0.9.2-dev.zip](https://github.com/pleonex/tinke/files/929934/Tinke-0.9.2-dev.zip)

Thanks!

**Comment by gingerbeardman** [comment]
This runs, thanks!
