### ISSUE TITLE
Automatically decompress files

### ISSUE THREAD

**Issue by gingerbeardman** [pleonex/tinke#53]
Would be good if it automatically decompressed a file when it is selected.

Maybe also an option to "decompress all"?

**Comment by pleonex** [comment]
This is already implemented although it's a little bit *hidden*. If you select a folder and click *Decompress* it will decompress/unpack all the subfiles recursively. For instance, you could select the top level *root* folder and click *Decompress* to decompress/unpack all the files of the game.

There is also a keyboard shortcut: select a file and press <kbd>d</kbd>

**Comment by gingerbeardman** [comment]
Superb, thanks!
