### ISSUE TITLE
"Buscar:" label not localised

### ISSUE THREAD

**Issue by gingerbeardman** [pleonex/tinke#55]
above instant search:

![screen shot 2017-04-18 at 16 12 54](https://cloud.githubusercontent.com/assets/49612/25138243/ebc1ff3a-2451-11e7-8395-2e5cbef28b5e.png)

**Comment by Taewong** [comment]
**Buscar** is the Spanish word for search.

**Comment by gingerbeardman** [comment]
@twse I'm aware of that, I just expect all the user interface strings to be in English when I select English.

**Comment by pleonex** [comment]
Thanks to @TemplarVolk it's fixed now 😄 . Thanks for reporting!
