### ISSUE TITLE
Compressing folders

### ISSUE THREAD

**Issue by researcher2312** [pleonex/tinke#57]
I am currently translating Professor Layton, there are thousands of .txt files compressed into .pcm folders. Currently I have to replace every single file and then pack them. Is there any way to compress the whole folder with files to .pcm file and then replace just the compressed file?

**Comment by milan2555** [comment]
I know this issue is almost 2 years old but what did you end up doing. (I'm in a similar situation)

**Comment by researcher2312** [comment]
It turns out that if you select the pcm file, then click the replace button and then select all the txt files at once (for example while holding shift), it will pack and replace them automatically. I guess this issue is pointless then :)
