### ISSUE TITLE
Problem with loading files due to .NET Framework?

### ISSUE THREAD

**Issue by Lvutir** [pleonex/tinke#77]
I try to open a ROM to get this error:
![Screenshot (669)](https://user-images.githubusercontent.com/68472297/87855243-42c72680-c917-11ea-9493-6bf197d95266.png) (This happens for every plugin.)
I followed the link to be told to go to the config file (app.config?) inside of the folder and tried changing <loadFromRemoteSources  to both 'true' and 'false' and neither worked. Does anyone know the solution for this problem?

This issue seems to only happen with the 9.2.0 version, the 9.0.0 works fine.

**Comment by pleonex** [comment]
Try to check the file properties of the plugin files (right click -> properties) to make sure they are not "blocked" due to downloading from Internet.

Otherwise I have no idea. Tinke was built with a quite old version of .NET Framework, so it could be an incompatibility with newer versions.

**Comment by Lvutir** [comment]
That seems to have worked. Prior I also have turned off all restrictions my anti-virus made. Tested other stuff but applied none of that stuff this time
Just manually selecting everything to be unblocked and anti-virus restrictions. Thank you for helping!
