### ISSUE TITLE
Mono on MacOS: The Carbon Driver has not been ported to 64bits

### ISSUE THREAD

**Issue by DualDestry** [pleonex/tinke#80]
Is this program really 32bit? The compiler specifically asks if your platform is x86 or x64 (and I picked x64), so am I doing something wrong here?

**Comment by pleonex** [comment]
Unfortunately there is nothing we can do about it. MacOS doesn't support anymore 32-bits applications (x86) and [Mono doesn't support 64-bits WinForms applications in MacOS](https://github.com/mono/mono/issues/6701). In that other GitHub issue there are some workarounds you may want to try (I don't have any Mac device so I can't).

**Comment by DualDestry** [comment]
Ok, thanks. It seems really weird that they'd have a 64bit version, but not have it actually work.
