### ISSUE TITLE
Possible Malware Infection

### ISSUE THREAD

**Issue by SuperPupperDoggo** [pleonex/tinke#81]
https://www.virustotal.com/gui/file/9dde1f1ed326151130f7541dc816f081cd7eb2272f4cb5622b5d22379d85b348/detection

just letting you know

**Comment by pleonex** [comment]
Re-analyzed and the false positive doesn't appear anymore. Thanks for let me know.
https://www.virustotal.com/gui/file/9dde1f1ed326151130f7541dc816f081cd7eb2272f4cb5622b5d22379d85b348/detection
