### ISSUE TITLE
Build errors on recent Linux distros

### ISSUE THREAD

**Issue by SgtMooshroom** [pleonex/tinke#86]
Ubuntu Unity 20.04

rm: cannot remove '/home/username/tinke-0.9/build/*.mdb': No such file or directory
rm: cannot remove '/home/username/tinke-0.9/build/Plugins/*.mdb': No such file or directory

Afterward, no binary is produced, and yes, I did install xbuild and xbuild-locale-extras

**Comment by SgtMooshroom** [comment]
Again
rm: cannot remove '/home/username/Downloads/tinke-0.9.1(1)/tinke-0.9.1/build/*.mdb': No such file or directory
rm: cannot remove '/home/username/Downloads/tinke-0.9.1(1)/tinke-0.9.1/build/Plugins/*.mdb': No such file or directory

**Comment by pleonex** [comment]
Make sure you can the latest version from the repo, I think the latest version of `compile.sh` shouldn't try to remove any .mdb file.
