### ISSUE TITLE
Windows prevents loading plugins

### ISSUE THREAD

**Issue by IncenyROMs** [pleonex/tinke#93]
I have an error with this
![20220314_220612](https://user-images.githubusercontent.com/101695243/158529754-130f8bc4-486e-4dbd-bdb0-ecd940831ace.jpg)
I install the Last. NET framework versión and all i need please help me.

**Comment by IncenyROMs** [comment]
Error loading the file

**Comment by pleonex** [comment]
That may happen if Windows _blocks_ downloaded files from Internet.
Right-click that DLL (`1stPlayable.dll`), go to Properties and make sure Windows didn't block the file. Also check the same for `Tinke.exe`.

![image](https://user-images.githubusercontent.com/3107481/158791508-8f786b9a-3e38-42ff-b111-b1ace69833ad.png)

**Comment by IncenyROMs** [comment]
I prove unlock in the tinke.exe file and 1stPlayable.dll and nothing change

**Comment by pleonex** [comment]
You may need to unlock all the files in the Tinke folder and plugins. Maybe it's possible via selecting the folder.

**Comment by yiliansource** [comment]
You can also unblock them by navigating to the plugins directory in Windows Powershell and running
```ps
dir -Path . | Unblock-File
```
