### ISSUE TITLE
How to add or remove files from NDS files

### ISSUE THREAD

**Issue by dananothername** [pleonex/tinke#97]
how to delete/ add files then compresse it to .nds

**Comment by pleonex** [comment]
Tinke cannot add or remove files from a NDS container. It can only modify its content.
The tool is deprecated in this repository, so there is no plan to add support for this.

**Comment by dananothername** [comment]
why did you close it
i still have issues 
![Screenshot_2022-11-26_06-44-07](https://user-images.githubusercontent.com/101902085/204087077-ce423f7a-677b-4bd6-85f8-d54343cd00fa.png)

**Comment by pleonex** [comment]
That issue from your screenshot is completely unrelated to this question.

**Comment by dananothername** [comment]
I'll build it to linux for now cause i can't restart the pc
and i still have some questions support
